In [4]:
import tensorflow as tf

In [5]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 73.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

In [6]:
# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

In [7]:
w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

In [9]:
# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize, Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [13]:
# Launch the graph in a session
sess = tf.Session()
# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
        

0 Cost:  6892.543 
Prediction:
 [221.49295 274.46423 266.60812 284.82953 220.98065]
10 Cost:  28.0125 
Prediction:
 [148.49954 186.75839 180.17563 190.71423 151.83601]
20 Cost:  27.927917 
Prediction:
 [148.29741 186.50775 179.93239 190.45213 151.6371 ]
30 Cost:  27.897821 
Prediction:
 [148.30045 186.50356 179.93207 190.45456 151.6325 ]
40 Cost:  27.867878 
Prediction:
 [148.30402 186.50003 179.93242 190.45767 151.62845]
50 Cost:  27.837967 
Prediction:
 [148.30759 186.49657 179.9328  190.46085 151.62442]
60 Cost:  27.80807 
Prediction:
 [148.31114 186.49306 179.9331  190.46394 151.62035]
70 Cost:  27.778254 
Prediction:
 [148.3147  186.48961 179.93347 190.46706 151.61629]
80 Cost:  27.748352 
Prediction:
 [148.31827 186.4861  179.93384 190.47021 151.61224]
90 Cost:  27.71867 
Prediction:
 [148.32182 186.48265 179.93419 190.47331 151.6082 ]
100 Cost:  27.68893 
Prediction:
 [148.32538 186.47919 179.93454 190.47644 151.60416]
110 Cost:  27.659313 
Prediction:
 [148.3289  186.47571 179.