In [2]:
import tensorflow as tf

In [1]:
x_data = [[73., 80., 75.], [93., 88., 93.], [89., 91., 90.], [96., 98., 100.], [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.],[142.]]

In [5]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [6]:
hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize, Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [7]:
# Launch the graph in a session
sess = tf.Session()
# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())

In [13]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  0.78341496 
Prediction:
 [[150.97054]
 [185.0963 ]
 [180.55249]
 [195.21463]
 [143.38779]]
10 Cost:  0.78085965 
Prediction:
 [[150.97305]
 [185.09453]
 [180.55322]
 [195.21538]
 [143.3853 ]]
20 Cost:  0.7783262 
Prediction:
 [[150.97559]
 [185.09279]
 [180.55397]
 [195.21613]
 [143.38284]]
30 Cost:  0.7758028 
Prediction:
 [[150.97812]
 [185.09105]
 [180.55473]
 [195.21687]
 [143.38039]]
40 Cost:  0.7732965 
Prediction:
 [[150.98062]
 [185.08931]
 [180.55547]
 [195.2176 ]
 [143.37793]]
50 Cost:  0.7707989 
Prediction:
 [[150.98314]
 [185.08757]
 [180.5562 ]
 [195.21834]
 [143.37549]]
60 Cost:  0.76831895 
Prediction:
 [[150.98563]
 [185.08583]
 [180.55695]
 [195.21909]
 [143.37305]]
70 Cost:  0.76584864 
Prediction:
 [[150.98811]
 [185.0841 ]
 [180.55766]
 [195.2198 ]
 [143.3706 ]]
80 Cost:  0.7633939 
Prediction:
 [[150.9906 ]
 [185.08238]
 [180.55843]
 [195.22055]
 [143.36818]]
90 Cost:  0.7609455 
Prediction:
 [[150.99306]
 [185.08066]
 [180.55913]
 [195.22127]
 [143.36574